movie = input("Enter your favorite movie: ")
ticket = int(input("how much cost for one ticket: "))
tickets = int(input("how many tickets you want to buy: "))
members = int(input("how many are there in your group: "))
print("The New movie is", movie) 
print("The cost of one ticket is", ticket)
print("We are planned to go",members)
print("The total tickets are",tickets)
print("The total cost of ticket is", ticket * members)
